### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by fdsam** [FaithZL/Paladin#22]
您好，我是在Window10上用cmake进行编译的，在编译embree库的时候出现了错误.
 "CMake Error at E:/cmaker/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find TBB (missing: EMBREE_TBB_INCLUDE_DIR EMBREE_TBB_LIBRARY
  EMBREE_TBBMALLOC_LIBRARY)"。
我是cmake的新手，不是很了解怎么使用。请问我要在哪个文件夹里下载Intel TBB库 和embree一起进行编译。

**Comment by FaithZL** [comment]
不好意思，现在这个仓库已经不维护了，而且，很久之前我也只在mac上开发，windows上构建失败的问题也没时间去解决，我的建议是，如果要运行代码的话，还是建议直接跑pbrt-v3，比较方便跑起来，paladin这个工程的意义在于有完整的注释以及推导过工程

**Comment by fdsam** [comment]
好的非常感谢

**Comment by fdsam** [comment]
> 不好意思，现在这个仓库已经不维护了，而且，很久之前我也只在mac上开发，windows上构建失败的问题也没时间去解决，我的建议是，如果要运行代码的话，还是建议直接跑pbrt-v3，比较方便跑起来，paladin这个工程的意义在于有完整的注释以及推导过工程

好的，非常感谢您的回复。
